# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f6381ee386c67bd98d5203738646e58b7a93065c8e3b6b02c500c6200b7a8dd52f60dac746d97b1330ef9463f598a99ea2de304607bcdcebf40a78353c3623

test:
  secret_key_base: 305e1be61c086bfe7f7fd1f9939101caefb8691fba85c98bc31120a1e9d34e5e5f3b5792cca9d05beda77b9ff0f2fd697a688a1905ff97df62050e5f9ef0add9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
